# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  steps:
  - script: docker build -t zeek .
- job: test
  dependsOn: build
  steps:
  - script: docker run -d --net=host -v /opt/bro/logs:/opt/bro/logs -v /opt/bro/spool:/opt/bro/spool --name zeek zeek
  - script: sleep 5
  - script: docker ps | grep -q bro
  - script: ps -ea | grep -q bro

